/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_g__rer_agent (void)
{
  GtkWidget *g__rer_agent;
  GtkWidget *notebook2;
  GtkWidget *fixed14;
  GtkWidget *entry24;
  GtkWidget *entry25;
  GtkWidget *entry26;
  GtkObject *spin_jour_adj;
  GtkWidget *spin_jour;
  GtkObject *spin_annee_adj;
  GtkWidget *spin_annee;
  GtkWidget *combobox_ajout;
  GtkWidget *label_echecajout;
  GtkWidget *entry30;
  GtkWidget *checkbutton1;
  GtkWidget *alignment56;
  GtkWidget *hbox56;
  GtkWidget *image56;
  GtkWidget *label149;
  GtkWidget *label_ajoutresult;
  GtkWidget *label147;
  GtkWidget *label113;
  GtkWidget *label109;
  GtkWidget *label108;
  GtkWidget *label111;
  GtkWidget *label112;
  GtkWidget *label115;
  GtkWidget *radiobutton_oui;
  GSList *radiobutton_oui_group = NULL;
  GtkWidget *alignment39;
  GtkWidget *hbox39;
  GtkWidget *image39;
  GtkWidget *label118;
  GtkWidget *radiobutton_non;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image37;
  GtkWidget *label114;
  GtkWidget *radiobutton_homme;
  GSList *radiobutton_homme_group = NULL;
  GtkWidget *radiobutton_femme;
  GtkWidget *button_ajouter;
  GtkWidget *alignment38;
  GtkWidget *hbox38;
  GtkWidget *image38;
  GtkWidget *label116;
  GtkWidget *button_retour_arwa;
  GtkWidget *alignment59;
  GtkWidget *hbox59;
  GtkWidget *image60;
  GtkWidget *label164;
  GtkWidget *label_ajout;
  GtkWidget *fixed15;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *entry29;
  GtkObject *spin_jourmod_adj;
  GtkWidget *spin_jourmod;
  GtkObject *spin_anneemod_adj;
  GtkWidget *spin_anneemod;
  GtkWidget *entry31;
  GtkWidget *label_modresult;
  GtkWidget *label153;
  GtkWidget *label123;
  GtkWidget *label122;
  GtkWidget *label119;
  GtkWidget *label120;
  GtkWidget *label121;
  GtkWidget *label139;
  GtkWidget *combobox_mod;
  GtkWidget *button_mod;
  GtkWidget *alignment43;
  GtkWidget *hbox43;
  GtkWidget *image43;
  GtkWidget *label127;
  GtkWidget *radiobutton_modhomme;
  GSList *radiobutton_modhomme_group = NULL;
  GtkWidget *radiobutton_modfemme;
  GtkWidget *radiobutton_modoui;
  GSList *radiobutton_modoui_group = NULL;
  GtkWidget *alignment41;
  GtkWidget *hbox41;
  GtkWidget *image41;
  GtkWidget *label125;
  GtkWidget *radiobutton_modnon;
  GtkWidget *alignment42;
  GtkWidget *hbox42;
  GtkWidget *image42;
  GtkWidget *label126;
  GtkWidget *button_rechmod;
  GtkWidget *image58;
  GtkWidget *checkbutton2;
  GtkWidget *alignment57;
  GtkWidget *hbox57;
  GtkWidget *image57;
  GtkWidget *label154;
  GtkWidget *label_modifier;
  GtkWidget *fixed16;
  GtkWidget *treeview1;
  GtkWidget *entry_spp;
  GtkWidget *button_supp;
  GtkWidget *alignment53;
  GtkWidget *hbox53;
  GtkWidget *image53;
  GtkWidget *label144;
  GtkWidget *label_suppresult;
  GtkWidget *label_affagent;
  GtkWidget *button_aff;
  GtkWidget *alignment52;
  GtkWidget *hbox52;
  GtkWidget *image52;
  GtkWidget *label143;
  GtkWidget *label_aff;
  GtkWidget *fixed18;
  GtkWidget *entry_rech;
  GtkWidget *label151;
  GtkWidget *label_rechresult;
  GtkWidget *button_rech;
  GtkWidget *alignment54;
  GtkWidget *hbox54;
  GtkWidget *image54;
  GtkWidget *label145;
  GtkWidget *label_rech;
  GtkWidget *fixed19;
  GtkWidget *treeview2;
  GtkWidget *label155;
  GtkWidget *entry_reser_rech;
  GtkWidget *label_reser_rech;
  GtkWidget *button_reser_rech;
  GtkWidget *alignment58;
  GtkWidget *hbox58;
  GtkWidget *image59;
  GtkWidget *label163;
  GtkWidget *label_reserrech;

  g__rer_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (g__rer_agent), _("G\303\251rer agent"));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (g__rer_agent), notebook2);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed14);

  entry24 = gtk_entry_new ();
  gtk_widget_show (entry24);
  gtk_fixed_put (GTK_FIXED (fixed14), entry24, 304, 48);
  gtk_widget_set_size_request (entry24, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 8226);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed14), entry25, 304, 88);
  gtk_widget_set_size_request (entry25, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed14), entry26, 304, 128);
  gtk_widget_set_size_request (entry26, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  spin_jour_adj = gtk_adjustment_new (4, 1, 31, 1, 10, 0);
  spin_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spin_jour_adj), 1, 0);
  gtk_widget_show (spin_jour);
  gtk_fixed_put (GTK_FIXED (fixed14), spin_jour, 336, 168);
  gtk_widget_set_size_request (spin_jour, 60, 27);

  spin_annee_adj = gtk_adjustment_new (2004, 1920, 2024, 1, 10, 0);
  spin_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spin_annee_adj), 1, 0);
  gtk_widget_show (spin_annee);
  gtk_fixed_put (GTK_FIXED (fixed14), spin_annee, 592, 168);
  gtk_widget_set_size_request (spin_annee, 68, 28);

  combobox_ajout = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_ajout);
  gtk_fixed_put (GTK_FIXED (fixed14), combobox_ajout, 416, 168);
  gtk_widget_set_size_request (combobox_ajout, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("f\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("juin "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("juillet "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("aout "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("novembre "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout), _("d\303\251cembre"));

  label_echecajout = gtk_label_new ("");
  gtk_widget_show (label_echecajout);
  gtk_fixed_put (GTK_FIXED (fixed14), label_echecajout, 232, 424);
  gtk_widget_set_size_request (label_echecajout, 296, 24);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed14), entry30, 304, 16);
  gtk_widget_set_size_request (entry30, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  checkbutton1 = gtk_check_button_new ();
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton1, 88, 320);
  gtk_widget_set_size_request (checkbutton1, 144, 40);

  alignment56 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment56);
  gtk_container_add (GTK_CONTAINER (checkbutton1), alignment56);

  hbox56 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox56);
  gtk_container_add (GTK_CONTAINER (alignment56), hbox56);

  image56 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox56), image56, FALSE, FALSE, 0);

  label149 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Confirmer</b></span>"));
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (hbox56), label149, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label149), TRUE);

  label_ajoutresult = gtk_label_new ("");
  gtk_widget_show (label_ajoutresult);
  gtk_fixed_put (GTK_FIXED (fixed14), label_ajoutresult, 136, 376);
  gtk_widget_set_size_request (label_ajoutresult, 488, 56);

  label147 = gtk_label_new (_("<span foreground=\"black\"><b>ID :</b></span>"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed14), label147, 228, 19);
  gtk_widget_set_size_request (label147, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label147), TRUE);

  label113 = gtk_label_new (_("<span foreground=\"black\"><b>Nom :</b></span>"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed14), label113, 216, 48);
  gtk_widget_set_size_request (label113, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label113), TRUE);

  label109 = gtk_label_new (_("<span foreground=\"black\"><b>Prenom :</b></span>"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed14), label109, 208, 88);
  gtk_widget_set_size_request (label109, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  label108 = gtk_label_new (_("<span foreground=\"black\"><b>CIN :</b></span>"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed14), label108, 216, 128);
  gtk_widget_set_size_request (label108, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label108), TRUE);

  label111 = gtk_label_new (_("<span foreground=\"black\"><b>Date de naissance :</b></span>"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed14), label111, 176, 168);
  gtk_widget_set_size_request (label111, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (label111), TRUE);

  label112 = gtk_label_new (_("<span foreground=\"black\"><b>Permis :</b></span>"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed14), label112, 200, 216);
  gtk_widget_set_size_request (label112, 104, 24);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  label115 = gtk_label_new (_("<span foreground=\"black\"><b>Sexe</b></span>"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed14), label115, 168, 264);
  gtk_widget_set_size_request (label115, 81, 32);
  gtk_label_set_use_markup (GTK_LABEL (label115), TRUE);

  radiobutton_oui = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_oui);
  gtk_fixed_put (GTK_FIXED (fixed14), radiobutton_oui, 336, 216);
  gtk_widget_set_size_request (radiobutton_oui, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_oui), radiobutton_oui_group);
  radiobutton_oui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_oui));

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (radiobutton_oui), alignment39);

  hbox39 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox39);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox39);

  image39 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox39), image39, FALSE, FALSE, 0);

  label118 = gtk_label_new_with_mnemonic (_("Oui"));
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox39), label118, FALSE, FALSE, 0);

  radiobutton_non = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_non);
  gtk_fixed_put (GTK_FIXED (fixed14), radiobutton_non, 432, 216);
  gtk_widget_set_size_request (radiobutton_non, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_non), radiobutton_oui_group);
  radiobutton_oui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_non));

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (radiobutton_non), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image37 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox37), image37, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic (_("Non"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox37), label114, FALSE, FALSE, 0);

  radiobutton_homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_homme);
  gtk_fixed_put (GTK_FIXED (fixed14), radiobutton_homme, 288, 272);
  gtk_widget_set_size_request (radiobutton_homme, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme), radiobutton_homme_group);
  radiobutton_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme));

  radiobutton_femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_femme);
  gtk_fixed_put (GTK_FIXED (fixed14), radiobutton_femme, 440, 272);
  gtk_widget_set_size_request (radiobutton_femme, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme), radiobutton_homme_group);
  radiobutton_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme));

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed14), button_ajouter, 312, 320);
  gtk_widget_set_size_request (button_ajouter, 112, 40);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment38);

  hbox38 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox38);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox38);

  image38 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox38), image38, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Ajouter</b></span>"));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox38), label116, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label116), TRUE);

  button_retour_arwa = gtk_button_new ();
  gtk_widget_show (button_retour_arwa);
  gtk_fixed_put (GTK_FIXED (fixed14), button_retour_arwa, 0, 0);
  gtk_widget_set_size_request (button_retour_arwa, 72, 32);

  alignment59 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment59);
  gtk_container_add (GTK_CONTAINER (button_retour_arwa), alignment59);

  hbox59 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox59);
  gtk_container_add (GTK_CONTAINER (alignment59), hbox59);

  image60 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox59), image60, FALSE, FALSE, 0);

  label164 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label164);
  gtk_box_pack_start (GTK_BOX (hbox59), label164, FALSE, FALSE, 0);

  label_ajout = gtk_label_new (_("<span foreground=\"black\"><b>Ajouter</b></span>"));
  gtk_widget_show (label_ajout);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label_ajout);
  gtk_label_set_use_markup (GTK_LABEL (label_ajout), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label_ajout), 0.46, 0.46);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed15);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed15), entry27, 304, 48);
  gtk_widget_set_size_request (entry27, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed15), entry28, 304, 88);
  gtk_widget_set_size_request (entry28, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed15), entry29, 304, 128);
  gtk_widget_set_size_request (entry29, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  spin_jourmod_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 0);
  spin_jourmod = gtk_spin_button_new (GTK_ADJUSTMENT (spin_jourmod_adj), 1, 0);
  gtk_widget_show (spin_jourmod);
  gtk_fixed_put (GTK_FIXED (fixed15), spin_jourmod, 336, 168);
  gtk_widget_set_size_request (spin_jourmod, 60, 27);

  spin_anneemod_adj = gtk_adjustment_new (1920, 1920, 2024, 1, 10, 0);
  spin_anneemod = gtk_spin_button_new (GTK_ADJUSTMENT (spin_anneemod_adj), 1, 0);
  gtk_widget_show (spin_anneemod);
  gtk_fixed_put (GTK_FIXED (fixed15), spin_anneemod, 584, 168);
  gtk_widget_set_size_request (spin_anneemod, 63, 29);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed15), entry31, 304, 16);
  gtk_widget_set_size_request (entry31, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  label_modresult = gtk_label_new ("");
  gtk_widget_show (label_modresult);
  gtk_fixed_put (GTK_FIXED (fixed15), label_modresult, 232, 376);
  gtk_widget_set_size_request (label_modresult, 328, 48);

  label153 = gtk_label_new (_("<span foreground=\"black\"><b>ID :</b></span>"));
  gtk_widget_show (label153);
  gtk_fixed_put (GTK_FIXED (fixed15), label153, 228, 19);
  gtk_widget_set_size_request (label153, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label153), TRUE);

  label123 = gtk_label_new (_("<span foreground=\"black\"><b>Nom :</b></span>"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed15), label123, 216, 48);
  gtk_widget_set_size_request (label123, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label123), TRUE);

  label122 = gtk_label_new (_("<span foreground=\"black\"><b>Prenom :</b></span>"));
  gtk_widget_show (label122);
  gtk_fixed_put (GTK_FIXED (fixed15), label122, 208, 88);
  gtk_widget_set_size_request (label122, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label122), TRUE);

  label119 = gtk_label_new (_("<span foreground=\"black\"><b>CIN :</b></span>"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed15), label119, 216, 128);
  gtk_widget_set_size_request (label119, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label119), TRUE);

  label120 = gtk_label_new (_("<span foreground=\"black\"><b>Date de naissance :</b></span>"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed15), label120, 176, 168);
  gtk_widget_set_size_request (label120, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (label120), TRUE);

  label121 = gtk_label_new (_("<span foreground=\"black\"><b>Permis :</b></span>"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed15), label121, 200, 216);
  gtk_widget_set_size_request (label121, 104, 24);
  gtk_label_set_use_markup (GTK_LABEL (label121), TRUE);

  label139 = gtk_label_new (_("<span foreground=\"black\"><b>Sexe</b></span>"));
  gtk_widget_show (label139);
  gtk_fixed_put (GTK_FIXED (fixed15), label139, 168, 264);
  gtk_widget_set_size_request (label139, 81, 32);
  gtk_label_set_use_markup (GTK_LABEL (label139), TRUE);

  combobox_mod = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), combobox_mod, 416, 168);
  gtk_widget_set_size_request (combobox_mod, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("f\303\251vrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("juin "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("juillet "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("aout "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("novembre "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mod), _("d\303\251cembre"));

  button_mod = gtk_button_new ();
  gtk_widget_show (button_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), button_mod, 312, 320);
  gtk_widget_set_size_request (button_mod, 112, 40);

  alignment43 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment43);
  gtk_container_add (GTK_CONTAINER (button_mod), alignment43);

  hbox43 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (alignment43), hbox43);

  image43 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox43), image43, FALSE, FALSE, 0);

  label127 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Modifier</b></span>"));
  gtk_widget_show (label127);
  gtk_box_pack_start (GTK_BOX (hbox43), label127, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label127), TRUE);

  radiobutton_modhomme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_modhomme);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton_modhomme, 288, 272);
  gtk_widget_set_size_request (radiobutton_modhomme, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modhomme), radiobutton_modhomme_group);
  radiobutton_modhomme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modhomme));

  radiobutton_modfemme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_modfemme);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton_modfemme, 440, 272);
  gtk_widget_set_size_request (radiobutton_modfemme, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modfemme), radiobutton_modhomme_group);
  radiobutton_modhomme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modfemme));

  radiobutton_modoui = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_modoui);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton_modoui, 336, 216);
  gtk_widget_set_size_request (radiobutton_modoui, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modoui), radiobutton_modoui_group);
  radiobutton_modoui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modoui));

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (radiobutton_modoui), alignment41);

  hbox41 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox41);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox41);

  image41 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image41);
  gtk_box_pack_start (GTK_BOX (hbox41), image41, FALSE, FALSE, 0);

  label125 = gtk_label_new_with_mnemonic (_("Oui"));
  gtk_widget_show (label125);
  gtk_box_pack_start (GTK_BOX (hbox41), label125, FALSE, FALSE, 0);

  radiobutton_modnon = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_modnon);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton_modnon, 432, 216);
  gtk_widget_set_size_request (radiobutton_modnon, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modnon), radiobutton_modoui_group);
  radiobutton_modoui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modnon));

  alignment42 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment42);
  gtk_container_add (GTK_CONTAINER (radiobutton_modnon), alignment42);

  hbox42 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox42);
  gtk_container_add (GTK_CONTAINER (alignment42), hbox42);

  image42 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox42), image42, FALSE, FALSE, 0);

  label126 = gtk_label_new_with_mnemonic (_("Non"));
  gtk_widget_show (label126);
  gtk_box_pack_start (GTK_BOX (hbox42), label126, FALSE, FALSE, 0);

  button_rechmod = gtk_button_new ();
  gtk_widget_show (button_rechmod);
  gtk_fixed_put (GTK_FIXED (fixed15), button_rechmod, 472, 16);
  gtk_widget_set_size_request (button_rechmod, 31, 29);

  image58 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_container_add (GTK_CONTAINER (button_rechmod), image58);

  checkbutton2 = gtk_check_button_new ();
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed15), checkbutton2, 88, 320);
  gtk_widget_set_size_request (checkbutton2, 144, 40);

  alignment57 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment57);
  gtk_container_add (GTK_CONTAINER (checkbutton2), alignment57);

  hbox57 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox57);
  gtk_container_add (GTK_CONTAINER (alignment57), hbox57);

  image57 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox57), image57, FALSE, FALSE, 0);

  label154 = gtk_label_new (_("<span foreground=\"black\"><b>Confirmer</b></span>"));
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (hbox57), label154, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label154, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label154), TRUE);

  label_modifier = gtk_label_new (_("<span foreground=\"black\"><b>Modifier</b></span>"));
  gtk_widget_show (label_modifier);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label_modifier);
  gtk_label_set_use_markup (GTK_LABEL (label_modifier), TRUE);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed16);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed16), treeview1, 168, 56);
  gtk_widget_set_size_request (treeview1, 768, 216);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1), TRUE);

  entry_spp = gtk_entry_new ();
  gtk_widget_show (entry_spp);
  gtk_fixed_put (GTK_FIXED (fixed16), entry_spp, 312, 328);
  gtk_widget_set_size_request (entry_spp, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_spp), 8226);

  button_supp = gtk_button_new ();
  gtk_widget_show (button_supp);
  gtk_fixed_put (GTK_FIXED (fixed16), button_supp, 176, 328);
  gtk_widget_set_size_request (button_supp, 112, 40);

  alignment53 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment53);
  gtk_container_add (GTK_CONTAINER (button_supp), alignment53);

  hbox53 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox53);
  gtk_container_add (GTK_CONTAINER (alignment53), hbox53);

  image53 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox53), image53, FALSE, FALSE, 0);

  label144 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Supprimer</b></span>"));
  gtk_widget_show (label144);
  gtk_box_pack_start (GTK_BOX (hbox53), label144, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label144), TRUE);

  label_suppresult = gtk_label_new ("");
  gtk_widget_show (label_suppresult);
  gtk_fixed_put (GTK_FIXED (fixed16), label_suppresult, 192, 384);
  gtk_widget_set_size_request (label_suppresult, 392, 48);

  label_affagent = gtk_label_new ("");
  gtk_widget_show (label_affagent);
  gtk_fixed_put (GTK_FIXED (fixed16), label_affagent, 176, 272);
  gtk_widget_set_size_request (label_affagent, 392, 48);

  button_aff = gtk_button_new ();
  gtk_widget_show (button_aff);
  gtk_fixed_put (GTK_FIXED (fixed16), button_aff, 8, 96);
  gtk_widget_set_size_request (button_aff, 104, 40);

  alignment52 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment52);
  gtk_container_add (GTK_CONTAINER (button_aff), alignment52);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment52), hbox52);

  image52 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image52);
  gtk_box_pack_start (GTK_BOX (hbox52), image52, FALSE, FALSE, 0);

  label143 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Afficher</b></span>"));
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (hbox52), label143, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label143), TRUE);

  label_aff = gtk_label_new (_("<span foreground=\"black\"><b>Afficher</b></span>"));
  gtk_widget_show (label_aff);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label_aff);
  gtk_label_set_use_markup (GTK_LABEL (label_aff), TRUE);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed18);

  entry_rech = gtk_entry_new ();
  gtk_widget_show (entry_rech);
  gtk_fixed_put (GTK_FIXED (fixed18), entry_rech, 216, 112);
  gtk_widget_set_size_request (entry_rech, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_rech), 8226);

  label151 = gtk_label_new (_("<span foreground=\"black\"><b>Saisiez l'ID \303\240 chercher</b></span>"));
  gtk_widget_show (label151);
  gtk_fixed_put (GTK_FIXED (fixed18), label151, 208, 56);
  gtk_widget_set_size_request (label151, 176, 32);
  gtk_label_set_use_markup (GTK_LABEL (label151), TRUE);

  label_rechresult = gtk_label_new ("");
  gtk_widget_show (label_rechresult);
  gtk_fixed_put (GTK_FIXED (fixed18), label_rechresult, 176, 216);
  gtk_widget_set_size_request (label_rechresult, 272, 184);

  button_rech = gtk_button_new ();
  gtk_widget_show (button_rech);
  gtk_fixed_put (GTK_FIXED (fixed18), button_rech, 248, 160);
  gtk_widget_set_size_request (button_rech, 104, 40);

  alignment54 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment54);
  gtk_container_add (GTK_CONTAINER (button_rech), alignment54);

  hbox54 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox54);
  gtk_container_add (GTK_CONTAINER (alignment54), hbox54);

  image54 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image54);
  gtk_box_pack_start (GTK_BOX (hbox54), image54, FALSE, FALSE, 0);

  label145 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Recherche</b></span>"));
  gtk_widget_show (label145);
  gtk_box_pack_start (GTK_BOX (hbox54), label145, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label145), TRUE);

  label_rech = gtk_label_new (_("<span foreground=\"black\"><b>Recherche</b></span>"));
  gtk_widget_show (label_rech);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label_rech);
  gtk_label_set_use_markup (GTK_LABEL (label_rech), TRUE);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed19);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview2, 200, 152);
  gtk_widget_set_size_request (treeview2, 760, 192);

  label155 = gtk_label_new (_("<span foreground=\"black\"><b>Saisiez un id de r\303\251servation </b></span>"));
  gtk_widget_show (label155);
  gtk_fixed_put (GTK_FIXED (fixed19), label155, 240, 48);
  gtk_widget_set_size_request (label155, 256, 40);
  gtk_label_set_use_markup (GTK_LABEL (label155), TRUE);

  entry_reser_rech = gtk_entry_new ();
  gtk_widget_show (entry_reser_rech);
  gtk_fixed_put (GTK_FIXED (fixed19), entry_reser_rech, 296, 96);
  gtk_widget_set_size_request (entry_reser_rech, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_reser_rech), 8226);

  label_reser_rech = gtk_label_new ("");
  gtk_widget_show (label_reser_rech);
  gtk_fixed_put (GTK_FIXED (fixed19), label_reser_rech, 168, 392);
  gtk_widget_set_size_request (label_reser_rech, 480, 64);

  button_reser_rech = gtk_button_new ();
  gtk_widget_show (button_reser_rech);
  gtk_fixed_put (GTK_FIXED (fixed19), button_reser_rech, 480, 88);
  gtk_widget_set_size_request (button_reser_rech, 104, 40);

  alignment58 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment58);
  gtk_container_add (GTK_CONTAINER (button_reser_rech), alignment58);

  hbox58 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox58);
  gtk_container_add (GTK_CONTAINER (alignment58), hbox58);

  image59 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox58), image59, FALSE, FALSE, 0);

  label163 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Recherche</b></span>"));
  gtk_widget_show (label163);
  gtk_box_pack_start (GTK_BOX (hbox58), label163, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label163), TRUE);

  label_reserrech = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Liste r\303\251servation</b></span>"));
  gtk_widget_show (label_reserrech);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 4), label_reserrech);
  gtk_label_set_use_markup (GTK_LABEL (label_reserrech), TRUE);

  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_oui, "toggled",
                    G_CALLBACK (on_radiobutton_oui_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_non, "toggled",
                    G_CALLBACK (on_radiobutton_non_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_homme, "toggled",
                    G_CALLBACK (on_radiobutton_homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_femme, "toggled",
                    G_CALLBACK (on_radiobutton_femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_arwa, "clicked",
                    G_CALLBACK (on_button_retour_arwa_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mod, "clicked",
                    G_CALLBACK (on_button_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modhomme, "toggled",
                    G_CALLBACK (on_radiobutton_modhomme_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modfemme, "toggled",
                    G_CALLBACK (on_radiobutton_modfemme_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modoui, "toggled",
                    G_CALLBACK (on_radiobutton_modoui_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modnon, "toggled",
                    G_CALLBACK (on_radiobutton_modnon_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_rechmod, "clicked",
                    G_CALLBACK (on_button_rechmod_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_supp, "clicked",
                    G_CALLBACK (on_button_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff, "clicked",
                    G_CALLBACK (on_button_aff_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rech, "clicked",
                    G_CALLBACK (on_button_rech_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_reser_rech, "clicked",
                    G_CALLBACK (on_button_reser_rech_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (g__rer_agent, g__rer_agent, "g__rer_agent");
  GLADE_HOOKUP_OBJECT (g__rer_agent, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (g__rer_agent, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (g__rer_agent, spin_jour, "spin_jour");
  GLADE_HOOKUP_OBJECT (g__rer_agent, spin_annee, "spin_annee");
  GLADE_HOOKUP_OBJECT (g__rer_agent, combobox_ajout, "combobox_ajout");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_echecajout, "label_echecajout");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (g__rer_agent, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment56, "alignment56");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox56, "hbox56");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image56, "image56");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label149, "label149");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_ajoutresult, "label_ajoutresult");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label147, "label147");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label113, "label113");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label109, "label109");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label108, "label108");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label111, "label111");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label112, "label112");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label115, "label115");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_oui, "radiobutton_oui");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image39, "image39");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label118, "label118");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_non, "radiobutton_non");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image37, "image37");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label114, "label114");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_homme, "radiobutton_homme");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_femme, "radiobutton_femme");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image38, "image38");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label116, "label116");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_retour_arwa, "button_retour_arwa");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image60, "image60");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label164, "label164");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_ajout, "label_ajout");
  GLADE_HOOKUP_OBJECT (g__rer_agent, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (g__rer_agent, spin_jourmod, "spin_jourmod");
  GLADE_HOOKUP_OBJECT (g__rer_agent, spin_anneemod, "spin_anneemod");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_modresult, "label_modresult");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label153, "label153");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label123, "label123");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label122, "label122");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label119, "label119");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label120, "label120");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label121, "label121");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label139, "label139");
  GLADE_HOOKUP_OBJECT (g__rer_agent, combobox_mod, "combobox_mod");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_mod, "button_mod");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment43, "alignment43");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image43, "image43");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label127, "label127");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_modhomme, "radiobutton_modhomme");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_modfemme, "radiobutton_modfemme");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_modoui, "radiobutton_modoui");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image41, "image41");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label125, "label125");
  GLADE_HOOKUP_OBJECT (g__rer_agent, radiobutton_modnon, "radiobutton_modnon");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment42, "alignment42");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image42, "image42");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label126, "label126");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_rechmod, "button_rechmod");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image58, "image58");
  GLADE_HOOKUP_OBJECT (g__rer_agent, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment57, "alignment57");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox57, "hbox57");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image57, "image57");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label154, "label154");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_modifier, "label_modifier");
  GLADE_HOOKUP_OBJECT (g__rer_agent, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (g__rer_agent, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry_spp, "entry_spp");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_supp, "button_supp");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment53, "alignment53");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image53, "image53");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label144, "label144");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_suppresult, "label_suppresult");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_affagent, "label_affagent");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_aff, "button_aff");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment52, "alignment52");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image52, "image52");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label143, "label143");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_aff, "label_aff");
  GLADE_HOOKUP_OBJECT (g__rer_agent, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry_rech, "entry_rech");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label151, "label151");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_rechresult, "label_rechresult");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_rech, "button_rech");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment54, "alignment54");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image54, "image54");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label145, "label145");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_rech, "label_rech");
  GLADE_HOOKUP_OBJECT (g__rer_agent, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (g__rer_agent, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label155, "label155");
  GLADE_HOOKUP_OBJECT (g__rer_agent, entry_reser_rech, "entry_reser_rech");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_reser_rech, "label_reser_rech");
  GLADE_HOOKUP_OBJECT (g__rer_agent, button_reser_rech, "button_reser_rech");
  GLADE_HOOKUP_OBJECT (g__rer_agent, alignment58, "alignment58");
  GLADE_HOOKUP_OBJECT (g__rer_agent, hbox58, "hbox58");
  GLADE_HOOKUP_OBJECT (g__rer_agent, image59, "image59");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label163, "label163");
  GLADE_HOOKUP_OBJECT (g__rer_agent, label_reserrech, "label_reserrech");

  return g__rer_agent;
}

